### ISSUE TITLE
add example of usage in a browser

### ISSUE THREAD

**Issue by titaniumbones** [orgapp/orgajs#35] opened 2019-09-16 15:04 UTC
I'd like to use org-js in a simple html page to render either a string or a file.  Do you have a working example of how to do this directly in an html page, using browserify, babel, webpack, or whatever else? Thanks!

**Comment by xiaoxinghu** [comment] 2019-10-11 00:17
I added a `playground` in the project. It's react based ([gatsbyjs](https://www.gatsbyjs.org)). Check out the `www` folder. It's on the [Index Page](https://github.com/orgapp/orgajs/blob/master/www/src/pages/index.js). It works fine on Chrome, but have regex issue on Firefox. Will have a look when I get around it. But PRs are always welcome.

**Comment by whacked** [comment] 2020-02-29 17:40
Firefox throws a syntax error because it does not yet have support for named capture groups in RegExp. See https://kangax.github.io/compat-table/es2016plus/ for compatibility matrix.

From what I can tell, named capture groups are currently only used for timestamp parsing in https://github.com/orgapp/orgajs/blob/c20a1de209443fa95b60fd653d4b081797173914/packages/orga/src/timestamp.ts#L11

but given the complexity of the expression I am not sure if improving compatibility of the expression is worth reducing its readability.

The [XRegExp](https://github.com/slevithan/xregexp) library appears to support named capture groups. I attempted to import it into orga and replaced the timestamp RegExp with `XRegExp`, but it doesn't supply the exact same API.

https://github.com/orgapp/orgajs/pull/43 is a working example. I **only** verified that the playground loads up in FF and that the live AST shows that a timestamp (including `beginDate` through `endTimeEnd` gets parsed), I **did not** run a complete test suite.

Since I am not familiar with the gastby toolchain, for reproducibility, here's what I did:
1. clone upstream orgajs (this) repo
2. load a nodejs10 + yarn environment: `nix-shell -p nodejs-10_x yarn` in 2 separate terminals
3. in one terminal, run `yarn run watch`, which actively compiles the ts files
4. in another terminal, run `cd www; yarn run develop`, which starts the gatsby webserver
5. in Firefox (73.0.1 Ubuntu), open http://localhost:8000. It opens the orgajs playground. Without the regex fix, the page will not load, showing a syntax error in lexer.js:29; that error link is not helpful and not the correct location.
6. *with* the regex fix in the PR, the playground loads, and you can enter an org date expression in the playground input and get an AST parse of `type: timestamp`

Thanks again for your excellent work.

**Comment by xiaoxinghu** [comment] 2020-04-16 23:01
changes merged, all tests passed, new package published. Please verify @whacked. Thanks for the help 👍.

**Closed by xiaoxinghu** 2020-04-16 23:01 UTC
